name: model-training
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  model-training:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Setup Python
        with:
          python-version: "3.9"
